import numpy as np
print('''习题4,求解矩阵方程AXB=C,X=(A_-1)C(B_-1)''')
print('''AX=B,X=(A_-1)B''')
A = np.array([[1,1,-1],[2,5,-4],[2,4,-5]])
B = np.array([[0,3],[4,8],[1,9]])
A_det=np.linalg.det(A)
#B_det=np.linalg.det(B) 不符合行列式的定义
A_1=np.linalg.inv(A)
X=np.dot(A_1,B)
print(np.around(X,decimals=2))
print('XA=B,X=B(A_-1)')
A = np.array([[1,-1,1],[2,1,0],[2,1,-1]])
B= np.array([[1,-1,3], [2,1,4]])
#XA=B,X=B（A_-1)
A_det=np.linalg.det(A)
A_1=np.linalg.inv(A)
print(np.dot(B,A_1))
print('''习题1.4-3,AXB=C,X=(A_-1)C(B_-1)''')
A= np.array([[-1,1,1], [1,-1,1],[1,1,-1]])
B = np.array([[2,1],[5,3]])
C = np.array([[1,2],[1,0],[-1,2]])
A_det=np.linalg.det(A)
B_det=np.linalg.det(B)
A_1=np.linalg.inv(A)
B_1=np.linalg.inv(B)
A_1C=np.dot(A_1,C)
X=np.dot(A_1C,B_1)
print(X)